# Generated by Django 5.1.7 on 2025-06-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Tel', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('Adresse', models.CharField(max_length=50)),
                ('mode_payement', models.CharField(choices=[('cahe', 'Cahe'), ('transfere Bancaire', 'Transfère Bancaire')], max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Travailleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naiss', models.DateField()),
                ('contacts', models.CharField(max_length=30)),
                ('date_embau', models.DateField()),
                ('jour_travailler', models.PositiveIntegerField()),
                ('jour_absen', models.PositiveIntegerField()),
                ('observation', models.TextField()),
                ('fonction', models.CharField(max_length=100)),
                ('renumere_par', models.CharField(choices=[('mois', 'Mois'), ('jour', 'Jour'), ('semaine', 'Semaine')], max_length=18)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('date_livraison', models.DateField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('data_exp', models.DateField(blank=True, null=True)),
                ('observation', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gproduit.categories')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gproduit.fournisseurs')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='partenaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('observation', models.TextField()),
                ('fournisseur', models.ManyToManyField(to='gproduit.fournisseurs')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='gproduit.produits')),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('total_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gproduit.client')),
            ],
        ),
        migrations.CreateModel(
            name='lignevente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gproduit.produits')),
                ('Vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lignes', to='gproduit.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_ach', models.DateTimeField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gproduit.produits')),
                ('Vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gproduit.vente')),
            ],
        ),
    ]
