# Generated by Django 5.2.4 on 2025-08-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gproduit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date_achat']},
        ),
        migrations.AlterField(
            model_name='travailleurs',
            name='fonction',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employé', 'Employé'), ('Stagiaire', 'Stagiaire'), ('Directeur', 'Directeur'), ('Secrétaire', 'Secrétaire'), ('Comptable', 'Comptable'), ('Technicien', 'Technicien'), ('Vendeur', 'Vendeur'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
